name: build

env:
  IMAGE_ORG: nobidev

on:
  create:
  push:
    branches:
      - 'develop'
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'changelogs/**'
      - 'deploy/helm/**'
      - 'docs/**'
      - 'design/**'
      - 'LICENSE'
      - 'MAINTAINERS'

jobs:
  provisioner-localpv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Set CI Tag
        run: |
          BRANCH="${GITHUB_REF##*/}"
          CI_TAG=${BRANCH#v}-ci
          if [ ${BRANCH} = "develop" ]; then
            CI_TAG="ci"
          fi
          echo "TAG=${CI_TAG}" >> $GITHUB_ENV

      - name: Set Build Date
        id: date
        run: |
          echo "::set-output name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%S%Z')"

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.IMAGE_ORG }}/openebs-provisioner-localpv
            ghcr.io/${{ env.IMAGE_ORG }}/dynamic-localpv-provisioner/provisioner-localpv
          tag-latest: false
          tag-custom-only: true
          tag-custom: |
            ${{ env.TAG }}

      - name: Print Tags
        run: |
          echo "${{ steps.docker_meta.outputs.tags }}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push multi-arch Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./buildscripts/provisioner-localpv/provisioner-localpv.Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            DBUILD_DATE=${{ steps.date.outputs.DATE }}
            DBUILD_REPO_URL=https://github.com/nobidev/dynamic-localpv-provisioner
